---
- name: GET FACTS FROM FORTIMANAGER
  hosts: fortimanager
  connection: local
  gather_facts: false
  vars:
    fortimanager_provider:
      username: "{{ primary_credentials['username'] }}"
      password: "{{ primary_credentials['password'] }}"
      host: "{{ ip_address }}"

  tasks:
    - name: GET FORTIMANAGER FACTS AND FORTIGATES AND CONFIGS
      fortimgr_facts:
        provider: "{{ fortimanager_provider }}"
        fortigates: "all"
        config_filter: "all"
      register: "my_facts"

    - name: DEBUG VAR
      debug:
        var: "my_facts"
